package com.example.customerrouting.enquiry;

public enum EnquiryCategory {
    CARD_PAYMENT_DISPUTE, CARD_FRAUD, CARD_SERVICES, ATM_QUERY, ATM_DISPUTE, BANK_TRANSFER, ACCOUNT_QUERY,
    IDENTITY_VERIFICATION, FEES_AND_CHARGES, LOAN_QUERY, MORTGAGE_QUERY, GENERAL_BANKING, MORTGAGE, PERSONAL_LOAN
}
